// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdquX_Ml2iaqGhFiZ-w3-MPsVuiEt0FNE',
    appId: '1:251401364587:web:0f6e761d0ff0cd3db3bd2e',
    messagingSenderId: '251401364587',
    projectId: 'find-your-restaurant-2efbc',
    authDomain: 'find-your-restaurant-2efbc.firebaseapp.com',
    storageBucket: 'find-your-restaurant-2efbc.appspot.com',
    measurementId: 'G-6YPCDVSHWS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9s7hQszcxMZ6ycQ9zbq21PF-apnTaIL4',
    appId: '1:251401364587:android:144a85562a8f5fe3b3bd2e',
    messagingSenderId: '251401364587',
    projectId: 'find-your-restaurant-2efbc',
    storageBucket: 'find-your-restaurant-2efbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYBEGi4XxavEOjDVsSwsyku2OumP1wCAI',
    appId: '1:251401364587:ios:1a1ec5601b5cb413b3bd2e',
    messagingSenderId: '251401364587',
    projectId: 'find-your-restaurant-2efbc',
    storageBucket: 'find-your-restaurant-2efbc.appspot.com',
    iosBundleId: 'com.example.findYourRestaurant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYBEGi4XxavEOjDVsSwsyku2OumP1wCAI',
    appId: '1:251401364587:ios:a7d8b003b5f09a44b3bd2e',
    messagingSenderId: '251401364587',
    projectId: 'find-your-restaurant-2efbc',
    storageBucket: 'find-your-restaurant-2efbc.appspot.com',
    iosBundleId: 'com.example.findYourRestaurant.RunnerTests',
  );
}
